//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTravelInTaiwan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class book
    {
        public int BookID { get; set; }
        public string Title { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string ISBN { get; set; }
        public string Language { get; set; }
        public string BookType { get; set; }
        public int Category { get; set; }
        public string BookSyllabus { get; set; }
        public byte[] BookImg { get; set; }
        public string BookIntro { get; set; }
        public int PublisherID { get; set; }
    
        public virtual publisher publisher { get; set; }
    }
}
