//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTravelInTaiwan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class food
    {
        public string id { get; set; }
        public string type { get; set; }
        public string title { get; set; }
        public string catalogs_id { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string business_hrs { get; set; }
        public string price { get; set; }
        public string Description { get; set; }
        public string route { get; set; }
        public string tianmama { get; set; }
        public string ImageUrl { get; set; }
        public string sc_id { get; set; }
        public string post_id { get; set; }
        public string link { get; set; }
        public Nullable<double> x { get; set; }
        public Nullable<double> y { get; set; }
        public string create_date { get; set; }
        public string modify_date { get; set; }
    }
}
