//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTravelInTaiwan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.order_item = new HashSet<order_item>();
            this.ratings = new HashSet<rating>();
            this.shoppingcarts = new HashSet<shoppingcart>();
            this.stocks = new HashSet<stock>();
            this.members = new HashSet<member>();
        }
    
        public int ProductID { get; set; }
        public int Price { get; set; }
        public int Quantity { get; set; }
        public int BookID { get; set; }
    
        public virtual ICollection<order_item> order_item { get; set; }
        public virtual ICollection<rating> ratings { get; set; }
        public virtual ICollection<shoppingcart> shoppingcarts { get; set; }
        public virtual ICollection<stock> stocks { get; set; }
        public virtual ICollection<member> members { get; set; }
    }
}
