//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTravelInTaiwan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewtype
    {
        public viewtype()
        {
            this.views = new HashSet<view>();
            this.place = new HashSet<place>();
        }
    
        public int Typenumber { get; set; }
        public string Typename { get; set; }
    
        public virtual ICollection<view> views { get; set; }
        public virtual ICollection<place> place { get; set; }
    }
}
