//------------------------------------------------------------------------------
// <auto-generated>
//    這個程式碼是由範本產生。
//
//    對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//    如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyTravelInTaiwan.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view
    {
        public view()
        {
            this.ratings = new HashSet<rating>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Lat { get; set; }
        public string Lng { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public int Viewtype { get; set; }
        public string Pt { get; set; }
        public string IconType { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<rating> ratings { get; set; }
        public virtual viewtype viewtype1 { get; set; }
    }
}
